### PR TITLE
Enable url processors and Blueprint support

### PR DESCRIPTION
**Pull request by stepheny**
By employing werkzeug.routing in WebSocketMiddleware, using a flask-style url processor was made possible. I merged register_blueprint method from flask.app so that websocket routes could be defined in separated files with Blueprints.

### CODE REVIEW

**Comment by zeekay** [comment]
This seems to break all the examples, no?

**Comment by stepheny** [comment]
Sorry for the previous corrupted commit. I've made a mistake that the middle ware raise a fault exception which breaks connections other than websockets. Now everything seems correct.
I'm using pyphon3 with a asyncio profile uwsgi, the WebSocket works fine.
I've tried to patch _gevent.py. Now the examples seem to work in a python2 gevent environment. As I'm not experienced with gevent, further test might be necessary.

**Comment by zeekay** [comment]
Sorry it's taken a while to get back to you. We've diverged a bit, if you update the PR against master I'll be happy to merge.

**Comment by stepheny** [comment]
It seems that the necessary modification about route and blueprint have already been merged into the master branch. A later bugfix on this pull request have been applied by hitigon in other commit. Well done.

**Pull request closed without merging**
